### ISSUE TITLE
failed on pulling image

### ISSUE THREAD

**Issue by bwomsm1** [significa/app-distribution-server#23]
When I am running:
`docker pull ghcr.io/significa/app-distribution-server:sha-8732770`

I am getting:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I am running on Mac OS 15.0

What is wrong?

**Comment by bwomsm1** [comment]
@tofran can you please assist me with that issue? thanks!

**Comment by tofran** [comment]
@bwomsm1 

That must be a problem of you not having Docker running on a Mac OS device.

Have you tried pulling any other image? Like:

```
docker pull alpine
```

**Comment by bwomsm1** [comment]
> @bwomsm1
> 
> That must be a problem of you not having Docker running on a Mac OS device.
> 
> Have you tried pulling any other image? Like:
> 
> ```
> docker pull alpine
> ```

Thanks for the quick response, 
I am getting the same error.

On that mac station I installed Docker only for CLI. I would rather not install the desktop app

**Comment by tofran** [comment]
There are many discussions online that cover installing docker on any system, with or without tooling like docker desktop.
I cannot endorse any specific, so please do your research.

Closing this issue as this falls outside the scope of this project.
