### ISSUE TITLE
How I can POST the ipa/apk from python script to the app-distribution-server service?

### ISSUE THREAD

**Issue by bwomsm1** [significa/app-distribution-server#28]

**Comment by tofran** [comment]
The instructions are quite clear in the readme:

```
curl -X "POST" \
  "http://localhost:8000/upload" \
  -H "Accept: application/json" \
  -H "X-Auth-Token: secret" \
  -H "Content-Type: multipart/form-data" \
  -F "app_file=@your-app-build.ipa"
```


If you are new to making requests in python, I recommend the[ Requests: HTTP for Humans™ library](https://requests.readthedocs.io/en/latest/).

See [POST a Multipart-Encoded File in the documentation](https://requests.readthedocs.io/en/latest/user/quickstart/#post-a-multipart-encoded-file).

Hope it helps. Good luck.

**Comment by bwomsm1** [comment]
@tofran I am using your server without the docker, and I would like to trigger it from python script instead of `curl` command, is it possible?

**Comment by tofran** [comment]
Yes just POST there, the CURL is the best way to document the request.
You can use any tool, language or automation, that is outside the scope of the project.

Here's an example:

```python
import requests

response = requests.post(
    "http://localhost:8000/upload",
    headers={
        "Accept": "application/json",
        "X-Auth-Token": "secret"
    },
    files={
        "app_file": open("your-app-build.ipa", "rb")
    },
)
```

**Comment by bwomsm1** [comment]
> Yes just POST there, the CURL is the best way to document the request. You can use any tool, language or automation, that is outside the scope of the project.
> 
> Here's an example:
> 
> ```python
> import requests
> 
> response = requests.post(
>     "http://localhost:8000/upload",
>     headers={
>         "Accept": "application/json",
>         "X-Auth-Token": "secret"
>     },
>     files={
>         "app_file": open("your-app-build.ipa", "rb")
>     },
> )
> ```

Thank you!
