### ISSUE TITLE
Feature request: upload UI and management page

### ISSUE THREAD

**Issue by Cregin** [significa/app-distribution-server#32]
I hope there will be an administrator page that can directly upload ipa files and delete ipa files instead of going through the terminal every time

**Comment by tofran** [comment]
Does using the swagger UI solve your use case?

![Screenshot 2024-12-17 at 10 36 18](https://github.com/user-attachments/assets/f6a21b00-7306-4025-8742-7c63b6f7bbd3)

[Available in `/docs`]

It is slightly technical, but the user uploading a build likely has a technical background. Do you think there's a reason to build a separate page for that? What is the use case?

**Comment by Cregin** [comment]
> Does using the swagger UI solve your use case?
> 
> ![Screenshot 2024-12-17 at 10 36 18](https://private-user-images.githubusercontent.com/5692603/396462942-f6a21b00-7306-4025-8742-7c63b6f7bbd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzIzNDMsIm5iZiI6MTczNDQzMjA0MywicGF0aCI6Ii81NjkyNjAzLzM5NjQ2Mjk0Mi1mNmEyMWIwMC03MzA2LTQwMjUtODc0Mi03YzYzYjZmN2JiZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTA0MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZmYzgwNjEwOTM3MmRkMDRkZWEwYTE1MTgyODQ1Y2I4NzNkZDc1ZmMzZTI4NTcwODhkMjUzYWNjMTRkNWZjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4DU3Kn6IxnkwJGdyNfAp9uyna-6ZkHa2kUTSA9ETlPQ)
> 
> [Available in `/docs`]
> 
> It is slightly technical, but the user uploading a build likely has a technical background. Do you think there's a reason to build a separate page for that? What is the use case?

This page, I can't delete the old ipa

**Comment by tofran** [comment]
You should be able to delete from here:

![Screenshot 2024-12-17 at 16 32 23](https://github.com/user-attachments/assets/04865f9f-9a7e-4125-9855-8b400f5853ac)

If the feature request is about the listing of old uploads, then please have a look at [this thread](https://github.com/significa/app-distribution-server/issues/20#issuecomment-2336493874).
